In [1]:
import numpy as np

In [2]:
# MATRIZ
A = np.array([[2,2,-1,0],
              [4,4,3,9],
              [0,1,3,7],
              [3,-3,-2,-4]])

B = np.array([[10],
              [20],
              [14],
              [0]])

In [3]:
# PROCEDIMIENTO
casicero = 1e-15 # Considerar como 0

In [4]:
# Evitar truncamiento en operaciones
A = np.array(A,dtype=float)

In [5]:
# Matriz aumentada
AB = np.concatenate((A,B),axis=1)
AB0 = np.copy(AB)

In [6]:
# Pivoteo parcial por filas
tamano = np.shape(AB)
n = tamano[0]
m = tamano[1]

In [7]:
# Para cada fila en AB
for i in range(0,n-1,1):
    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dondemax = np.argmax(columna)
    
    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal
        
AB1 = np.copy(AB)

In [8]:
# eliminacion hacia adelante
for i in range(0,n-1,1):
    pivote = AB[i,i]
    adelante = i + 1
    for k in range(adelante,n,1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
AB2 = np.copy(AB)

# elimina hacia atras
ultfila = n-1
ultcolumna = m-1
for i in range(ultfila,0-1,-1):
    pivote = AB[i,i]
    atras = i-1 
    for k in range(atras,0-1,-1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
    # diagonal a unos
    AB[i,:] = AB[i,:]/AB[i,i]
X = np.copy(AB[:,ultcolumna])
X = np.transpose([X])


# SALIDA
print('Matriz aumentada:')
print(AB0)
print('Pivoteo parcial por filas')
print(AB1)
print('eliminacion hacia adelante')
print(AB2)
print('eliminación hacia atrás')
print(AB)
print('solución de X: ')
print(X)

Matriz aumentada:
[[ 2.  2. -1.  0. 10.]
 [ 4.  4.  3.  9. 20.]
 [ 0.  1.  3.  7. 14.]
 [ 3. -3. -2. -4.  0.]]
Pivoteo parcial por filas
[[ 4.  4.  3.  9. 20.]
 [ 3. -3. -2. -4.  0.]
 [ 0.  1.  3.  7. 14.]
 [ 2.  2. -1.  0. 10.]]
eliminacion hacia adelante
[[  4.           4.           3.           9.          20.        ]
 [  0.          -6.          -4.25       -10.75       -15.        ]
 [  0.           0.           2.29166667   5.20833333  11.5       ]
 [  0.           0.           0.           1.18181818  12.54545455]]
eliminación hacia atrás
[[  1.           0.           0.           0.          -1.56923077]
 [ -0.           1.          -0.          -0.          -2.98461538]
 [  0.           0.           1.           0.         -19.10769231]
 [  0.           0.           0.           1.          10.61538462]]
solución de X: 
[[ -1.56923077]
 [ -2.98461538]
 [-19.10769231]
 [ 10.61538462]]
