In [1]:
import numpy as np

In [2]:
fx  = lambda x: 3*(x**4) - 2*(x**2) + 3*x -5
dfx = lambda x: 12*(x**3) -4*x + 3

In [3]:
x0 = 2
tolera = 0.00001

In [4]:
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[2.0000e+00 1.5495e+00 4.5055e-01]
 [1.5495e+00 1.2565e+00 2.9290e-01]
 [1.2565e+00 1.1147e+00 1.4190e-01]
 [1.1147e+00 1.0823e+00 3.2328e-02]
 [1.0823e+00 1.0808e+00 1.5004e-03]
 [1.0808e+00 1.0808e+00 3.1042e-06]]
raiz en:  1.0808205188546975
con error de:  3.1042028585392956e-06
